version: '3.1'
services:
  hc:
    build: ./docker/headless-chrome
    restart: always
    shm_size: '128mb'
    ports:
      - "9222:9222"
    networks:
      app_net:
        ipv4_address: 172.30.0.2

  web:
    build: ./docker/php
    restart: always
    links:
      - hc
    ports:
      - "8080:80"
    volumes:
      - ./web/:/var/www/html
    networks:
      app_net:
        ipv4_address: 172.30.0.3

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24